# Generated by Django 4.2.20 on 2025-04-06 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('expected_at', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('paid', models.BooleanField(default=False, verbose_name='Foi Pago?')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('notes', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donor', verbose_name='Doador')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.company')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
            },
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='check_amount_positive'),
        ),
    ]
