# Generated by Django 4.2.20 on 2025-05-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expected_at',
            field=models.DateField(verbose_name='Vencimento'),
        ),
    ]
