# Generated by Django 4.2.20 on 2025-04-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thankyoumessage',
            options={'verbose_name': 'Agradecimento', 'verbose_name_plural': 'Agradecimentos'},
        ),
    ]
