# Generated by Django 4.2.20 on 2025-04-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'permissions': [('can_update_paid', 'Can update paid field')], 'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
    ]
