# Generated by Django 4.2.20 on 2025-05-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_thankyoumessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thankyoumessage',
            options={'verbose_name': 'Agradecimento', 'verbose_name_plural': 'Mensagem de Agradecimentos'},
        ),
    ]
