# Generated by Django 4.2.20 on 2025-04-09 16:07

import core.models.company
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1, verbose_name='Tipo de pessoa')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.person')),
                ('logo_file', models.ImageField(blank=True, default='images/logo.png', null=True, upload_to=core.models.company.logo_directory_path, verbose_name='Logo')),
                ('cnae', models.CharField(blank=True, max_length=10, null=True, verbose_name='CNAE')),
                ('iest', models.CharField(blank=True, max_length=32, null=True, verbose_name='Inscrição Estadual')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.person')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Data de admissão')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Data de desligamento')),
                ('ctps', models.CharField(blank=True, max_length=100, null=True, verbose_name='CTPS (Carteira de Trabalho)')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Salário')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='legalentity', serialize=False, to='core.person', verbose_name='Pessoa')),
                ('cnpj', models.CharField(blank=True, max_length=32, null=True, verbose_name='CNPJ')),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome fantasia')),
                ('state_registration', models.CharField(blank=True, max_length=32, null=True, verbose_name='Inscrição estadual')),
                ('responsible', models.CharField(blank=True, max_length=32, null=True, verbose_name='Responsável')),
                ('tax_regime', models.CharField(blank=True, choices=[('LR', 'Lucro Real'), ('LP', 'Lucro Presumido'), ('SN', 'Simples Nacional'), ('SE', 'Simples Nacional, excesso sublimite de receita bruta')], max_length=2, null=True, verbose_name='Regime tributário')),
                ('suframa', models.CharField(blank=True, max_length=16, null=True, verbose_name='SUFRAMA')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('type', models.CharField(choices=[('M', 'Celular'), ('F', 'Fixo'), ('C', 'Comercial')], max_length=1, verbose_name='Tipo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Telefone principal?')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.person', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=32, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=32, null=True, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='core.person', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('is_primary', models.BooleanField(default=False, verbose_name='E-mail principal?')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.person', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, choices=[('UNI', 'Único'), ('RES', 'Residencial'), ('COM', 'Comercial'), ('COB', 'Cobrança'), ('ENT', 'Entrega'), ('OUT', 'Outro')], max_length=3, null=True, verbose_name='Tipo de endereço')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=64, null=True, verbose_name='Bairro')),
                ('complement', models.CharField(blank=True, max_length=64, null=True, verbose_name='Complemento')),
                ('country', models.CharField(blank=True, default='Brasil', max_length=32, null=True, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='Cidade')),
                ('postal_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='CEP')),
                ('state', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('EX', 'EX'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=3, null=True, verbose_name='Estado (UF)')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Endereço principal?')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.person', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(limit_choices_to={'person_type': 'J'}, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_company', to='auth.group')),
                ('company', models.ForeignKey(limit_choices_to={'person_type': 'J'}, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Funcionário Vinculado',
                'verbose_name_plural': 'Funcionários Vinculados',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.person')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='core.company')),
            ],
            options={
                'verbose_name': 'Doador',
                'verbose_name_plural': 'Doadores',
            },
            bases=('core.person',),
        ),
    ]
