# Generated by Django 4.2.20 on 2025-04-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_primary_address_per_person',
        ),
    ]
