/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.application.form.donor.dialog;

import domain.model.Donor;
import domain.service.DonorService;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import ui.application.Application;

/**
 *
 * @author cezar.britez
 */
public class DonorSearchDialog extends javax.swing.JDialog {

    private DonorService donorService;
    private Donor selectedDonor = null;
    private List<Donor> donors;

    /**
     * Creates new form DonorSearchDialog
     */
    public DonorSearchDialog(java.awt.Frame parent, boolean modal, DonorService donorService) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);  // Para centralizar na tela
        this.donorService = donorService;
        filter(jTextField1.getText());

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filter(jTextField1.getText());
            }
        });

        this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "close");

        this.getRootPane().getActionMap().put("close", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                dispose();
            }
        });

    }

    private void filter(String query) {
        // Aplica o filtro com base no texto digitado
        this.donors = this.donorService.findByQuery(Application.loggedUser(), query);
        updateTable(this.donors);
    }

    private void updateTable(List<Donor> donors) {
        // Obtem o modelo da tabela
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Limpa os dados existentes
        model.setRowCount(0);

        // Adiciona os dados da lista de doadores
        for (Donor donor : donors) {
            StringBuilder phones = new StringBuilder(); // Use StringBuilder para eficiência

            for (var contact : donor.getContacts()) {
                if (phones.length() > 0) {
                    phones.append(","); // Adiciona vírgula somente se já houver conteúdo
                }
                phones.append(contact.getPhone());
            }

            model.addRow(new Object[]{
                donor.getId(),
                donor.getName(),
                phones.toString()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Telefones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            selectDonor();
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void selectDonor() {
        int selectedRow = jTable1.getSelectedRow(); // Obtém a linha selecionada
        if (selectedRow != -1) {
            // Recupera os dados da linha selecionada
            var donor = this.donors.get(selectedRow);
            // Passa o resultado para o pai do diálogo
            disposeWithResult(donor);
        }
    }

    private void disposeWithResult(Donor donor) {
        this.selectedDonor = donor; // Define o doador selecionado
        this.dispose(); // Fecha o diálogo
    }

    public Donor getSelectedDonor() {
        return selectedDonor; // Retorna o doador selecionado ao pai
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
