name: Java Multi-Platform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, x86]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Reescrever o pom.xml para usar o Java 19
      - name: Update pom.xml to Java 19
        if: matrix.arch == 'x86'  # Condição que verifica se a arquitetura é x86
        run: |
          sed -i 's#<maven.compiler.source>.*</maven.compiler.source>#<maven.compiler.source>19</maven.compiler.source>#' pom.xml
          sed -i 's#<maven.compiler.target>.*</maven.compiler.target>#<maven.compiler.target>19</maven.compiler.target>#' pom.xml
          # Garantir que a versão do plugin de compilação também seja configurada corretamente
          sed -i 's#<source>.*</source>#<source>19</source>#' pom.xml
          sed -i 's#<target>.*</target>#<target>19</target>#' pom.xml

      # Configura a versão do Java com base na arquitetura
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.arch == 'x86' && '19' || '21' }}
          architecture: ${{ matrix.arch }}
          distribution: 'temurin'
          cache: maven

      # Compilar e testar com Maven
      - name: Build and Test with Maven
        run: mvn clean install -DskipTests=false

      # Passo 4: Empacotar com jpackage
      - name: Package with jpackage for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          jpackage --type app-image --input target/ --name Ebenezer --main-jar Ebenezer-1.0-SNAPSHOT.jar --main-class com.ebenezer.pos.Ebenezer --java-options "-Xmx512m"
          ls

      - name: Package with jpackage for Windows
        if: matrix.os == 'windows-latest'
        run: |
          jpackage --type exe --input target/ --name Ebenezer --main-jar Ebenezer-1.0-SNAPSHOT.jar --main-class com.ebenezer.pos.Ebenezer --java-options "-Xmx512m" --dest target/windows

      - name: Package with jpackage for macOS
        if: matrix.os == 'macos-latest'
        run: |
          jpackage --type dmg --input target/ --name Ebenezer --main-jar Ebenezer-1.0-SNAPSHOT.jar --main-class com.ebenezer.pos.Ebenezer --java-options "-Xmx512m" --dest target/macos

      # Passo 5: Upload de artefatos (arquivos gerados pelo Maven e pacotes)
      - name: Upload Maven build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ebenezer-${{ matrix.os }}-${{ matrix.arch }}   # Nome único com ID da execução
          path: |
            Ebenezer/
            target/windows/*
            target/macos/*
            
      # Passo 6: Baixar artefatos para o ambiente local
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ebenezer-${{ matrix.os }}-${{ matrix.arch }}  # Nome do artefato gerado no passo anterior
          path: artifacts/  # Diretório onde os artefatos serão extraídos
          
      - uses: svenstaro/upload-release-action@v2
        name: Upload binaries to release
        if: ${{ github.event_name == 'push' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ebenezer-${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_name: ebenezer-${{ matrix.os }}-${{ matrix.arch }}.zip
          tag: ${{ github.ref }}
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          overwrite: true