name: Build Windows 32-bit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python 32-bit
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x86'  # 👈 importante para 32 bits

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pywebview pyinstaller

      - name: Build com PyInstaller
        run: |
          pyinstaller --onefile --noconsole client.py

      - name: Upload binário
        uses: actions/upload-artifact@v3
        with:
          name: app-win32
          path: dist/client.exe
